urls.py
from django.conf.urls.defaults import *
#from students import views
# The next two lines enable the admin and load each admin.py file:
from django.views.generic.simple import direct_to_template
from django.contrib import admin
from django.views.generic.simple import direct_to_template
admin.autodiscover()

urlpatterns = patterns('',
    #(r'^admin/(.*)', admin.site.root),
    #(r'^marks_add/', views.marks_add),
    #(r'^attendance_add/', views.attendance_add),
    (r'^admin/ams/home/', 'sms.ams.views.admin_home'),
    #(r'^admin/(.*)', admin.site.root),
    (r'^admin/', include(admin.site.urls)),
    (r'^marks_add/', 'sms.students.views.marks_add'),
    (r'^attendance_add/', 'sms.students.views.attendance_add'),
    (r'^report/', 'sms.students.views.report'),
    (r'^ams/', 'sms.ams.views.get_barcode'),
    (r'^leave/', 'sms.ams.views.app_leave'),
    (r'^leave_report/', 'sms.ams.views.report_leave'),
    (r'^ams_report/', 'sms.ams.views.monthly_report'),
    (r'^ams_daily_report/', 'sms.ams.views.daily_report'),
    (r'^ams_display/', 'sms.ams.views.ams_display'),
    (r'^fee/', 'sms.fees.views.fee_receipt'),
    (r'^fee_receipt/', 'sms.fees.views.reprint_receipt'),
    (r'^fee_report/', 'sms.fees.views.fee_report'),
    (r'^reportPDF/', 'sms.students.views.report_pdf'),
    (r'^certificatePDF/', 'sms.students.views.certificate_pdf'),
    (r'^cardsPDF/', 'sms.students.views.cards_pdf'),
    (r'^schoolLeavingPDF/', 'sms.students.views.school_leaving_pdf'),
    (r'^fee_collection/', 'sms.fees.views.fee_collection'),
    (r'^ams_dayrules/', 'sms.ams.views.add_dayrules'),
    (r'^competition_add/', 'sms.students.views.competition_add'),
    (r'^elocution_add/', 'sms.students.views.elocution_add'),
    (r'^project_add/', 'sms.students.views.project_add'),
    (r'^abhivyaktivikas_add/', 'sms.students.views.abhivyaktivikas_add'),
    (r'^competitiveexam_add/', 'sms.students.views.competitiveexam_add'),
    (r'^cocurricular_add/', 'sms.students.views.cocurricular_add'),
    (r'^socialactivity_add/', 'sms.students.views.socialactivity_add'),
    (r'^physicalfitnessinfo_add/', 'sms.students.views.physicalfitnessinfo_add'),
    (r'^workexperience_add/', 'sms.students.views.workexperience_add'),
    (r'^physicaleducation_add/', 'sms.students.views.physicaleducation_add'),
    (r'^thinkingskill_add/', 'sms.students.views.thinkingskill_add'),
    (r'^socialskill_add/', 'sms.students.views.socialskill_add'),
    (r'^emotionalskill_add/', 'sms.students.views.emotionalskill_add'),
    (r'^attitudetowardsschool_add/', 'sms.students.views.attitudetowardsschool_add'),
    (r'^values_add/', 'sms.students.views.values_add'),
    (r'^medicalreport_add/', 'sms.students.views.medicalreport_add'),
    (r'^scrap_add/', 'sms.students.views.scrap_add'),
    (r'^names_sheet/','students.views.generate_name_columns'),
    (r'^display_report/(?P<regno>\d+)/(?P<year>\d{4}\-\d{4})','students.views.display_report'),
    (r'^marksTablesPDF/', 'students.views.marks_tables_pdf'),
(r'^accounts/', include('registration.urls')),
#(r'^accounts/', include('registration.backends.default.urls')),
(r'^$', direct_to_template,  { 'template': 'index.html' }, 'index'),
    #(r'^pravesh/add', 'sms.pravesh.views.add'),
    #(r'^pravesh/student/(\d+)/edit/?','sms.pravesh.views.edit'),
    #(r'^pravesh/hallticket/(\d+)/?','sms.pravesh.views.display_hallticket'),
    #(r'^pravesh/generate_hallticket','sms.pravesh.views.generate_hallticket'),
    #(r'^pravesh/generate_report','sms.pravesh.views.generate_classreport'),
    #(r'^pravesh/?','sms.pravesh.views.index'),
    ##(r'^pravesh/student/(\d+)/edit/?$','sms.pravesh.views.edit'),
#
    (r'^jp_sms/admin/ams/home/', 'sms.ams.views.admin_home'),
    #(r'^jp_sms/admin/(.*)', admin.site.root),
    (r'^jp_sms/admin/', include(admin.site.urls)),
    (r'^jp_sms/marks_add/', 'sms.students.views.marks_add'),
    (r'^jp_sms/attendance_add/', 'sms.students.views.attendance_add'),
    (r'^jp_sms/report/', 'sms.students.views.report'),
    (r'^jp_sms/ams/$', 'sms.ams.views.get_barcode'),
    (r'^jp_sms/leave/$', 'sms.ams.views.app_leave'),
    (r'^jp_sms/ams_report/', 'sms.ams.views.monthly_report'),
    (r'^jp_sms/ams_daily_report/', 'sms.ams.views.daily_report'),
    (r'^jp_sms/fee_report/', 'sms.fees.views.fee_report'),
    (r'^jp_sms/fee/', 'sms.fees.views.fee_receipt'),
    (r'^jp_sms/fee_receipt/', 'sms.fees.views.reprint_receipt'),
    (r'^jp_sms/reportPDF/', 'sms.students.views.report_pdf'),
    (r'^jp_sms/ams_display/', 'sms.ams.views.ams_display'),
    (r'^jp_sms/certificatePDF/', 'sms.students.views.certificate_pdf'),
    (r'^jp_sms/cardsPDF/', 'students.views.cards_pdf'),
    (r'^jp_sms/schoolLeavingPDF/', 'sms.students.views.school_leaving_pdf'),
    (r'^jp_sms/fee_collection/', 'sms.fees.views.fee_collection'),
    (r'^jp_sms/ams_dayrules/', 'sms.ams.views.add_dayrules'),
    (r'^jp_sms/competition_add/', 'sms.students.views.competition_add'),
    (r'^jp_sms/elocution_add/', 'sms.students.views.elocution_add'),
    (r'^jp_sms/project_add/', 'sms.students.views.project_add'),
    (r'^jp_sms/abhivyaktivikas_add/', 'sms.students.views.abhivyaktivikas_add'),
    (r'^jp_sms/competitiveexam_add/', 'sms.students.views.competitiveexam_add'),
    (r'^jp_sms/cocurricular_add/', 'sms.students.views.cocurricular_add'),
    (r'^jp_sms/socialactivity_add/', 'sms.students.views.socialactivity_add'),
    (r'^jp_sms/physicalfitnessinfo_add/', 'sms.students.views.physicalfitnessinfo_add'),
    (r'^jp_sms/workexperience_add/', 'sms.students.views.workexperience_add'),
    (r'^jp_sms/physicaleducation_add/', 'sms.students.views.physicaleducation_add'),
    (r'^jp_sms/thinkingskill_add/', 'sms.students.views.thinkingskill_add'),
    (r'^jp_sms/socialskill_add/', 'sms.students.views.socialskill_add'),
    (r'^jp_sms/emotionalskill_add/', 'sms.students.views.emotionalskill_add'),
    (r'^jp_sms/attitudetowardsschool_add/', 'sms.students.views.attitudetowardsschool_add'),
    (r'^jp_sms/values_add/', 'sms.students.views.values_add'),
    (r'^jp_sms/medicalreport_add/', 'sms.students.views.medicalreport_add'),
    (r'^jp_sms/names_sheet/','students.views.generate_name_columns'),
    (r'^jp_sms/display_report/(?P<regno>\d+)/(?P<year>\d{4}\-\d{4})','students.views.display_report'),
    (r'^jp_sms/marksTablesPDF/', 'students.views.marks_tables_pdf'),
(r'^jp_sms/accounts/', include('registration.urls')),
(r'^jp_sms/?$', direct_to_template,  { 'template': 'index.html' }, 'index'),
    #(r'^jp_sms/pravesh/add', 'sms.pravesh.views.add'),
    #(r'^jp_sms/pravesh/hallticket/(\d+)/?','sms.pravesh.views.display_hallticket'),
    #(r'^jp_sms/pravesh/generate_hallticket','sms.pravesh.views.generate_hallticket'),
    #(r'^jp_sms/pravesh/student/(\d+)/edit/?$','sms.pravesh.views.edit'),
    #(r'^jp_sms/pravesh/generate_report','sms.pravesh.views.generate_classreport'),
    ##(r'^jp_sms/pravesh/edit/(\d+)/?', 'sms.pravesh.views.edit'),
    #(r'^jp_sms/pravesh/?','sms.pravesh.views.index'),
    (r'^parents/','students.views.student_summary'),
    (r'^jp_sms/parents/','students.views.student_summary'),
    (r'^parents/fee','fees.views.fee_parent'),
    (r'^sms_send/','students.views.send_sms_students'),
    (r'^jp_sms/sms_send/','students.views.send_sms_students'),
    (r'^additionalinformation_add/', 'students.views.additionalinfo_add'),
    (r'^jp_sms/additionalinformation_add/', 'students.views.additionalinfo_add'),
    ##(r'^accounts/', include('registration.backends.default.urls')),
    (r'^accounts/', include('registration.urls')),
    (r'^$', direct_to_template,  { 'template': 'index.html' }, 'index'),
    (r'^pravesh/add', 'sms.pravesh.views.add'),
    (r'^pravesh/hallticket/(\d+)/?$','sms.pravesh.views.display_hallticket'),
    (r'^pravesh/student/(\d+)/edit/?$','sms.pravesh.views.edit'),
    (r'^pravesh/generate_hallticket','sms.pravesh.views.generate_hallticket'),
    (r'^pravesh/generate_report','sms.pravesh.views.generate_classreport'),
    (r'^pravesh/?','sms.pravesh.views.index'),
    (r'^mailinglist/display', 'sms.mailinglist.views.display'),
    #(r'^useradd/', views.user_add),
    # ... the rest of your URLs here ...
)

ams/models.py
from django.db import models
from django import forms

# import variables
from sms.ams.vars import *


# Create your models here.
class AcademicYear(models.Model):
    Id = models.AutoField(primary_key=True)
    Title = models.CharField(max_length=30)
    StartDate = models.DateField()
    EndDate = models.DateField()
    Status = models.PositiveIntegerField(choices=YEAR_CHOICES)

    def __unicode__(self):
        return "%s" % (self.Title)


class Category(models.Model):
    Id = models.PositiveIntegerField(primary_key=True)
    Description = models.CharField(max_length=30)

    def __unicode__(self):
        return "%s" % (self.Description)

    class Meta:
        verbose_name_plural = "Categories"


class User(models.Model):
    Barcode = models.PositiveIntegerField(primary_key=True)
    Category = models.ForeignKey(Category)
    Name = models.CharField(max_length=50)
    Email = models.EmailField(unique=True)
    Phone = models.CharField(max_length=15)
    TerminationDate = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return "%s" % (self.Name)

    def __str__(self):
        return "%s" % (self.Name)


class UserStatus(models.Model):
    Barcode = models.ForeignKey(User)
    Status = models.CharField(max_length=1, choices=STATUS_CHOICES)


class UserJoiningDate(models.Model):
    Barcode = models.ForeignKey(User)
    JoiningDate = models.DateField()


class ForgotCheckout(models.Model):
    Barcode = models.ForeignKey(User)
    Date = models.DateField()
    Status = models.PositiveIntegerField(choices=FORGOT_CHECKOUT_CHOICES)


class TimeRules(models.Model):
    Type = models.CharField(max_length=30, primary_key=True)
    TimeIn = models.TimeField()
    LateIn = models.TimeField()
    HalfIn = models.TimeField()
    HalfOut = models.TimeField()
    EarlyOut = models.TimeField()
    TimeOut = models.TimeField()

    def __unicode__(self):
        return "%s" % (self.Type)


class DayRules(models.Model):
    Category = models.ForeignKey(Category)
    Barcode = models.PositiveIntegerField(null=True, blank=True)
    Day = models.PositiveIntegerField(
        choices=DAY_CHOICES,
        null=True,
        blank=True
    )
    Date = models.DateField(null=True, blank=True)
    Type = models.ForeignKey(TimeRules)

    def __unicode__(self):
        return "%s %s %s %s  -  %s" % (
            self.Category,
            self.Barcode,
            self.Day,
            self.Date,
            self.Type
        )


class Attendance(models.Model):
    Barcode = models.ForeignKey(User)
    Date = models.DateField(null=True, blank=True)
    Remark = models.CharField(max_length=1, choices=REMARK_CHOICES)
    Year = models.ForeignKey(AcademicYear)
    Comment = models.CharField(max_length=30, null=True, blank=True)
    def __unicode__(self):
        return '%s' % (self.Barcode)
    

class LeaveAttendance(models.Model):
    Barcode = models.ForeignKey(User)
    Date = models.DateField(null=True, blank=True)
    Remark = models.CharField(max_length=1, choices=REMARK_CHOICES)


class TempAttendance(models.Model):
    Barcode = models.ForeignKey(User)
    Remark = models.CharField(max_length=1, choices=REMARK_CHOICES)


class TimeRecords(models.Model):
    Barcode = models.ForeignKey(User)
    Type = models.CharField(max_length=1, choices=STATUS_CHOICES)
    Date = models.DateField()
    Time = models.TimeField()


class Leaves(models.Model):
    Barcode = models.ForeignKey(User)
    ApplicationDate = models.DateField()
    LeaveDate = models.DateField()
    ApprovalDate = models.DateField(null=True, blank=True)
    Type = models.PositiveIntegerField(choices=LEAVE_CHOICES)
    Status = models.PositiveIntegerField(choices=LEAVESTATUS_CHOICES)
    Reason = models.CharField(max_length=30, null=True, blank=True)

    def __unicode__(self):
        return "%s %s %s" % (self.Barcode, self.LeaveDate, self.Status)

    class Meta:
        verbose_name_plural = "Leaves"


class LeavesBalance(models.Model):
    Barcode = models.ForeignKey(User)
    Type = models.PositiveIntegerField(choices=LEAVE_CHOICES)
    Days = models.FloatField()


class LeaveRules(models.Model):
    Category = models.ForeignKey(Category)
    Type = models.PositiveIntegerField(choices=LEAVE_CHOICES)
    Days = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = "Leave Rules"


class EncashLeaves(models.Model):
    Barcode = models.ForeignKey(User)
    Days = models.PositiveIntegerField()
    Status = models.PositiveIntegerField(choices=LEAVESTATUS_CHOICES)

    class Meta:
        verbose_name_plural = "Encash Leaves"


class Overtime(models.Model):
    Barcode = models.ForeignKey(User)
    Date = models.DateField()
    ApprovalDate = models.DateField(null=True, blank=True)
    Hours = models.FloatField()
    Status = models.PositiveIntegerField(choices=LEAVESTATUS_CHOICES)

    class Meta:
        verbose_name_plural = "Overtime"


class LeaveForm(forms.Form):
    Category = forms.ModelChoiceField(queryset=Category.objects.all())
    Barcode = forms.ModelChoiceField(queryset=User.objects.all())
    FromDate = forms.DateField(widget=forms.DateTimeInput, required=False)
    ToDate = forms.DateField(widget=forms.DateTimeInput, required=False)
    Days = forms.IntegerField(required=False)
    Type = forms.ChoiceField(choices=LEAVE_CHOICES)
    Reason = forms.CharField(max_length=30, required=False)


class ReportForm(forms.Form):
    Category = forms.ModelChoiceField(queryset=Category.objects.all())
    Barcode = forms.ModelChoiceField(queryset=User.objects.all())
    FromDate = forms.DateField(widget=forms.DateTimeInput)
    ToDate = forms.DateField(widget=forms.DateTimeInput)


class DailyReportForm(forms.Form):
    Category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False
    )
    Date = forms.DateField(widget=forms.DateTimeInput)


class DayRulesForm(forms.Form):
    FromDate = forms.DateField(widget=forms.DateTimeInput)
    ToDate = forms.DateField(widget=forms.DateTimeInput)
    Category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False
    )
    Barcode = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False
    )
    Type = forms.ModelChoiceField(
        queryset=TimeRules.objects.all(),
        required=False
    )


class LeaveReportForm(forms.Form):
    Category = forms.ModelChoiceField(queryset=Category.objects.all())
    Barcode = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False
    )

ams/forms.py
from django import forms

from sms.ams.vars import *
from sms.ams.models import *
    

templates/ams/dailyreport.html
<html>
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6707232-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div align="center">

<h2>
ATTENDANCE: Daily Report
</h2><br/>

<form name="report" action="/ams_daily_report/" method="post">
<table>
{{ form.as_table }}
</table>
<h3>Date format: yyyy-mm-dd</h3>
<b>{{ message }}</b><br/><br/>
<input type="submit" value="Generate Report"/>
</form>

</div>
<div align="center">
<h2>
Daily Report : {{date}}
</h2><br/>
	<table border="1" cellspacing="5" cellpadding="0">
	<tr><th>User</th><th>Time In</th><th>Time Out</th><th>Remark</th></tr>
	{% for row in report %}
	<tr><td>{{row.user}}</td><td>{{row.ti}}</td><td>{{row.to}}</td><td>{{row.rem}}</td></tr>
	{% endfor %}
	</table>
	<br/>
	<b>
	Late:{{late}} &nbsp&nbsp
	Half:{{half}} &nbsp&nbsp
	Absent:{{absent}}
	</b>
</div>

</body>
</html>

templates/ams/dayrules.html
<html>
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6707232-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<script language="javascript">
function statusform()
{
 document.dayrule.addrules.value = 2;
 document.dayrule.submit();
}

function submitform()
{
 document.dayrule.addrules.value = 1;
 document.dayrule.submit();
}
 
</script>
<body>
<div align="center">

<h2>
DayRules Form
</h2><br/>

<form name="dayrule" action="/ams_dayrules/" method="post">
<table>
{{ form.as_table }}
</table>
<br/><h3>Date format: yyyy-mm-dd</h3>
<b>{{ message }}</b><br/><br/>
<input type="submit" value="Add Rules" onClick="submitform()"/>
<input type="submit" value="Check Status" onClick="statusform()"/>
<input type="hidden" name="addrules" value="1"/>
</form>

</div>
<br/>

<div align="center">
<h2>
Date Rules
</h2><br/>
	<table border="1" cellspacing="5" cellpadding="0">
		<tr><th>Date</th> <th>Day</th> <th>Barcode</th> <th>Category</th> <th>Time Rule</th> </tr>
	
			{% for row in daterules %}
			<tr>
				<td>{{ row.dater.Date}}</td><td>{{ row.daystr }}</td><td>{{ row.dater.Barcode }}</td>
				<td>{{ row.dater.Category}}</td><td>{{ row.dater.Type }}</td>
			</tr>
			{% endfor %}
	</table>
</div>

<div align="center">
<h2>
Day Rules
</h2><br/>
	<table border="1" cellspacing="5" cellpadding="0">
		<tr><th>Day</th> <th>Barcode</th> <th>Category</th> <th>Time Rule</th> </tr>
	
			{% for row in dayrules %}
			<tr>
				<td>{{ row.daystr }}</td><td>{{ row.dayr.Barcode }}</td>
				<td>{{ row.dayr.Category}}</td><td>{{ row.dayr.Type }}</td>
			</tr>
			{% endfor %}
	</table>
</div>

</body>
</html>

templates/ams/leavereport.html
<html>
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6707232-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<script lannguage="javascript">
function setdisabled(disabled)
{
 document.leave.Barcode.disabled = disabled;
 document.leave.Category.disabled = disabled;
}
</script>
<body onload="setdisabled({{disabled}})">
<div align="center">

<h2>
Leave Report
</h2><br/>

<form name="leave_report" action="/leave_report/" method="post">
<table>
{{ form.as_table }}
</table>
<br/><b>{{ message }}</b><br/><br/>
<input type="submit" value="Check Status" onClick="setdisabled(false);document.leave_report.submit()"/>
</form>

</div>
<br/>

<div id="LeaveBalance" name="LeaveBalance" align="center">
<h2>
Leave Summary
</h2><br/>
	<table border="1" cellspacing="5" cellpadding="0">
		<tr><th>User</th> <th colspan=2>Casual</th> <th colspan=2>Sick</th> <th colspan=2>Earned</th> 
		<th>Absent</th> <th>Half Days</th> <th>Late remarks</th> <th>Forgot checkout</th> </tr>
		<tr><th></th> <th>Taken</th><th>Balance</th> <th>Taken</th><th>Balance</th> <th>Taken</th><th>Balance</th> 
		<th></th> <th></th> <th></th> <th></th> </tr>
	
			{% for row in data %}
			<tr>
				<td>{{ row.usr}}</td> 
				<td>{{ row.casualtaken}}</td> <td>{{ row.casualbal}}</td> 
				<td>{{ row.sicktaken}}</td> <td>{{ row.sickbal}}</td> 
				<td>{{ row.earnedtaken}}</td> <td>{{ row.earnedbal}}</td> 
				<td>{{ row.absent}}</td> <td>{{ row.half}}</td> <td>{{ row.late}}</td> <td>{{ row.forgot}}</td>
			</tr>
			{% endfor %}
	</table>
</div>

</body>
</html>

templates/ams/report.html
<html>
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6707232-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
<div align="center">

<h2>
ATTENDANCE: Monthly Report
</h2><br/>

<form name="report" action="/ams_report/" method="post">
<table>
{{ form.as_table }}
</table>
<br/><h3>Date format: yyyy-mm-dd</h3>
<b>{{ message }}</b><br/><br/>
<input type="submit" value="Generate Report"/>
</form>

</div>
<div align="center">
<h2>
Report
</h2><br/>
	<table border="1" cellspacing="5" cellpadding="0">
	<tr><th>Date</th><th>Day</th><th>Time In</th><th>Time Out</th><th>Remark</th></tr>
	{% for row in report %}
	<tr><td>{{row.date}}</td><td>{{row.day}}</td><td>{{row.ti}}</td><td>{{row.to}}</td><td>{{row.rem}}</td></tr>
	{% endfor %}
	</table>
	<br/>
	<b>
	Late:{{late}} &nbsp&nbsp
	Half:{{half}} &nbsp&nbsp
	Absent:{{absent}}
	</b>
</div>

</body>
</html>

templates/ams/useradd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us" >
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6707232-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<title>Add user | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/media/css/forms.css" />



<script type="text/javascript" src="../../../jsi18n/"></script>
<script type="text/javascript" src="/media/js/core.js"></script>
<script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />

</head>


<body class="ams-user change-form">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name">Django administration</h1>

        </div>
        
        <div id="user-tools">Welcome, <strong>admin</strong>. <a href="/admin/password_change/">Change password</a> / <a href="/admin/logout/">Log out</a></div>
        
        
    </div>
    <!-- END Header -->
    

<div class="breadcrumbs">
     <a href="../../../">Home</a> &rsaquo;
     <a href="../../">Ams</a> &rsaquo; 
     <a href="../">Users</a> &rsaquo; 
     Add user
</div>

    

        

    <!-- Content -->

    <div id="content" class="colM">
        
        <h1>Add user</h1>
        <div id="content-main">



<form enctype="multipart/form-data" action="" method="post" id="user_form">
<div>





  <fieldset class="module aligned ">
  
  
  
      <div class="form-row Barcode  ">
      
      
      <div>
          
              <label for="id_Barcode" class="required">Barcode:</label><input id="id_Barcode" type="text" class="vIntegerField" name="Barcode" />
          
          
      </div>
      
      </div>
  
      <div class="form-row Category  ">
      
      
      <div>

          
              <label for="id_Category" class="required">Category:</label><select name="Category" id="id_Category">
<option value="" selected="selected">---------</option>
<option value="0">Teacher</option>
</select><a href="../../../ams/category/add/" class="add-another" id="add_id_Category" onclick="return showAddAnotherPopup(this);"> <img src="/media/img/admin/icon_addlink.gif" width="10" height="10" alt="Add Another"/></a>
          
          
      </div>
      
      </div>
  
      <div class="form-row Name  ">
      
      
      <div>

          
              <label for="id_Name" class="required">Name:</label><input id="id_Name" type="text" class="vTextField" name="Name" maxlength="30" />
          
          
      </div>
      
      </div>
  
</fieldset>









<div class="submit-row" >
<input type="submit" value="Save" class="default" name="_save" />


<input type="submit" value="Save and add another" name="_addanother"  />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>



   <script type="text/javascript">document.getElementById("id_Barcode").focus();</script>


<script type="text/javascript">

</script>


</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>

</div>
<!-- END Container -->

</body>
</html>